version: "3.8"
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=Arian
      - POSTGRES_PASSWORD=40S4r3dder!
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
